In [1]:
import pandas as pd
import numpy as np 

In [2]:
df = pd.read_csv('Final_user_dataset1.csv')

df = df.fillna('')

df.drop_duplicates(keep=False, inplace=True)

df

Unnamed: 0 To which gender identity do you most identify?  \
0            0                                         Female   
1            1                                           Male   
2            2                                         Female   
3            3                                         Female   
4            4                                         Female   
..         ...                                            ...   
60          65                                         Female   
61          66                                         Female   
62          67                                           Male   
63          68                                         Female   
64          69                                           Male   

   In which city do you (currently) live?   \
0                                Rotterdam   
1                                Rotterdam   
2                               Rotterdam    
3                                Rotterdam   
4                                Rotterdam   
..                                     ...   
60                                 Utrecht   
61                               Rotterdam   
62                                Schiedam   
63                               Amsterdam   
64                              Zoetermeer   

   What is the highest degree or level of education you have completed?  \
0                                         High School                     
1                                     Master's Degree                     
2                                         High School                     
3                                         High School                     
4                                         High School                     
..                                                ...                     
60                                  Bachelor's Degree                     
61                                  Bachelor's Degree                     
62                                       Trade School                     
63                                  Bachelor's Degree                     
64                                        High School                     

               What is your present religion, if any?  \
0                     Atheist (do not believe in God)   
1                               Nothing in particular   
2                               Nothing in particular   
3                     Atheist (do not believe in God)   
4                               Nothing in particular   
..                                                ...   
60  Protestant (United Church of Canada, Anglican,...   
61                              Nothing in particular   
62                    Atheist (do not believe in God)   
63                    Atheist (do not believe in God)   
64                              Nothing in particular   

             How would you describe your personality?  \
0                                                       
1   Energetic person who trives to get the best ou...   
2      Sensitive, caring, independent, enthusiastic     
3                                                       
4                            Spontaneous and cheerful   
..                                                ...   
60                              introvert, interested   
61          trustworthy, direct, assertive and caring   
62                              Extroverted introvert   
63                          outgoing, relaxed, social   
64                                            postive   

    I see myself as someone who...has an active imagination  \
0                                                   4         
1                                                   4         
2                                                   4         
3                                                   4         
4                                                   4         
..                   

In [3]:
#Rename all columns
df.rename(columns={'To which gender identity do you most identify?':'Gender', 'What is your age?':'Age', 'In which city do you (currently) live? ':'Location', 'What is the highest degree or level of education you have completed?':'Education', 'What is your present religion, if any?':'Religion', 'How would you describe your personality?':'Personality', 'I see myself as someone who...has an active imagination':'Imagination', 'I see myself as someone who... has few artistic interests':'Artistic', 'I see myself as someone who... is outgoing, sociable':'Sociable', 'I see myself as someone who... is reserved':'Reserved', 'I see myself as someone who... tends to be lazy':'Lazy', 'I see myself as someone who... gets nervous easily':'Nervous', 'I see myself as someone who... is generally trusting':'Trusting',
                  'I see myself as someone who... does a thorough job':'Thorough', 'I see myself as someone who... is relaxed, handles stress well':'Relaxed', 'I see myself as someone who... tends to find fault with others':'Fault_others', 'What are your hobbies? ':'Hobbies', 'Where are you very passionate about?    (This can be anything, e.g. your love for pets, certain news topic, sports, something related to your hobbies.)':'Passions', 'How would you describe your perfect match for a friendship? ':'Perfect_match', 'What characteristics does a potential friend / social connection need to have? ':'Characteristics_friend'}, inplace=True)

#delete information in brackets in column religion 
df['Religion'] = df['Religion'].str.split('(').str[0]
# df = df.astype(str)
# df['Relaxed'] = df['Relaxed'].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65 entries, 0 to 64
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Unnamed: 0              65 non-null     int64 
 1   Gender                  65 non-null     object
 2   Location                65 non-null     object
 3   Education               65 non-null     object
 4   Religion                65 non-null     object
 5   Personality             65 non-null     object
 6   Imagination             65 non-null     int64 
 7   Artistic                65 non-null     int64 
 8   Sociable                65 non-null     int64 
 9   Reserved                65 non-null     int64 
 10  Lazy                    65 non-null     object
 11  Nervous                 65 non-null     int64 
 12  Trusting                65 non-null     object
 13  Thorough                65 non-null     object
 14  Relaxed                 65 non-null     object
 15  Fault_ot

# Recommendation system 1 (numerical and categorical variables)

In [5]:
#Fill empty row with '3' to be able to transform columns to integers
df.loc[df.index[18], 'Relaxed'] = "3"
df.loc[df.index[23], 'Fault_others'] = "3"
df.loc[df.index[61], 'Thorough'] = "3"
df.loc[df.index[64], 'Thorough'] = "3"
df.loc[df.index[64], 'Trusting'] = "3"
df.loc[df.index[64], 'Lazy'] = "3"

df.loc[20, "Relaxed"]


4.0

In [6]:
#transform the two 'object' columns to intergers
df['Relaxed'] = df['Relaxed'].astype(int)
df['Fault_others'] = df['Fault_others'].astype(int)
df['Thorough'] = df['Thorough'].astype(int)
df['Trusting'] = df['Trusting'].astype(int)
df['Lazy'] = df['Lazy'].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65 entries, 0 to 64
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Unnamed: 0              65 non-null     int64 
 1   Gender                  65 non-null     object
 2   Location                65 non-null     object
 3   Education               65 non-null     object
 4   Religion                65 non-null     object
 5   Personality             65 non-null     object
 6   Imagination             65 non-null     int64 
 7   Artistic                65 non-null     int64 
 8   Sociable                65 non-null     int64 
 9   Reserved                65 non-null     int64 
 10  Lazy                    65 non-null     int64 
 11  Nervous                 65 non-null     int64 
 12  Trusting                65 non-null     int64 
 13  Thorough                65 non-null     int64 
 14  Relaxed                 65 non-null     int64 
 15  Fault_ot

In [7]:
#create new df based on numerical and categorical variables
df_num_cat = df[['Education', 'Religion', 'Imagination', 'Artistic', 'Sociable', 'Reserved', 'Lazy', 'Nervous', 'Trusting', 'Thorough', 'Relaxed', 'Fault_others']]


df_num_cat.head()

Education               Religion  Imagination  Artistic  Sociable  \
0      High School               Atheist             4         3         4   
1  Master's Degree  Nothing in particular            4         1         4   
2      High School  Nothing in particular            4         2         4   
3      High School               Atheist             4         3         4   
4      High School  Nothing in particular            4         1         5   

   Reserved  Lazy  Nervous  Trusting  Thorough  Relaxed  Fault_others  
0         2     2        4         2         3        1             1  
1         4     3        5         5         4        2             4  
2         2     4        4         3         4        2             1  
3         2     2        4         2         3        1             1  
4         2     4        5         5         4        2             3

In [8]:
#Create dummy variables for categorical columns
df_num_cat = df_num_cat.join(df_num_cat.Education.str.get_dummies("|"))
df_num_cat = df_num_cat.join(df_num_cat.Religion.str.get_dummies("|"))


del df_num_cat['Education']
del df_num_cat['Religion']

df_num_cat.head()

Imagination  Artistic  Sociable  Reserved  Lazy  Nervous  Trusting  \
0            4         3         4         2     2        4         2   
1            4         1         4         4     3        5         5   
2            4         2         4         2     4        4         3   
3            4         3         4         2     2        4         2   
4            4         1         5         2     4        5         5   

   Thorough  Relaxed  Fault_others  ...  Trade School  Agnostic   Atheist   \
0         3        1             1  ...             0          0         1   
1         4        2             4  ...             0          0         0   
2         4        2             1  ...             0          0         0   
3         3        1             1  ...             0          0         1   
4         4        2             3  ...             0          0         0   

   Catholic   Hindu  Muslim  Nothing in particular  \
0          0      0       0                      0   
1          0      0       0                      1   
2          0      0       0                      1   
3          0      0       0                      0   
4          0      0       0                      1   

   Officially catholic but I do not believe  Prefer Not to Say  Protestant   
0                                         0                  0            0  
1                                         0                  0            0  
2                                         0                  0            0  
3                                         0                  0            0  
4                                         0                  0            0  

[5 rows x 25 columns]

In [9]:
#create similarity scores
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(df_num_cat)
print(similarity)


[[1.         0.88651968 0.95292578 ... 0.8501661  0.87953676 0.89676876]
 [0.88651968 1.         0.92514915 ... 0.94024416 0.86011083 0.9040868 ]
 [0.95292578 0.92514915 1.         ... 0.91615051 0.8952787  0.93848349]
 ...
 [0.8501661  0.94024416 0.91615051 ... 1.         0.90020669 0.92489316]
 [0.87953676 0.86011083 0.8952787  ... 0.90020669 1.         0.93897748]
 [0.89676876 0.9040868  0.93848349 ... 0.92489316 0.93897748 1.        ]]


In [10]:
#Add index instead of names to preserve respondents privacy
df_num_cat['User'] = np.arange(len(df_num_cat))

In [11]:
#create matrix of the similarity scores
df_num_cat = pd.DataFrame(similarity, columns=df_num_cat.index, index=df_num_cat['User']).reset_index()
df_num_cat.head()

User         0         1         2         3         4         5         6  \
0     0  1.000000  0.886520  0.952926  1.000000  0.914240  0.811362  0.911854   
1     1  0.886520  1.000000  0.925149  0.886520  0.968910  0.768074  0.965172   
2     2  0.952926  0.925149  1.000000  0.952926  0.967603  0.834208  0.934893   
3     3  1.000000  0.886520  0.952926  1.000000  0.914240  0.811362  0.911854   
4     4  0.914240  0.968910  0.967603  0.914240  1.000000  0.800341  0.946769   

          7         8  ...        55        56        57        58        59  \
0  0.898781  0.906447  ...  0.914240  0.860975  0.944443  0.901670  0.916582   
1  0.893651  0.917520  ...  0.934306  0.928355  0.936575  0.929139  0.893814   
2  0.932406  0.930319  ...  0.926603  0.936130  0.974157  0.930745  0.902134   
3  0.898781  0.906447  ...  0.914240  0.860975  0.944443  0.901670  0.916582   
4  0.889499  0.918180  ...  0.923077  0.944695  0.953572  0.913230  0.861329   

         60        61        62        63        64  
0  0.871531  0.865065  0.850166  0.879537  0.896769  
1  0.960516  0.914830  0.940244  0.860111  0.904087  
2  0.919551  0.904695  0.916151  0.895279  0.938483  
3  0.871531  0.865065  0.850166  0.879537  0.896769  
4  0.939482  0.917098  0.925054  0.893453  0.921605  

[5 rows x 66 columns]

# Recommendation system 2 (text-based)

In [12]:
#Merge two columns because of the similarity in answers 
df['Interests'] = df['Passions']+ ' ' +df['Hobbies']

del df['Passions']
del df['Hobbies']

# Drop duplicate words
df['Interests'] = df['Interests'].str.replace(r'\b(\w+)(\s+\1)+\b', r'\1')

In [13]:
#Merge two columns because of the similarity in answer from every user
df['Perfect_match'] = df['Perfect_match']+ ' ' +df['Characteristics_friend']

del df['Characteristics_friend']

# Drop duplicate words
df['Perfect_match'] = df['Perfect_match'].str.replace(r'\b(\w+)(\s+\1)+\b', r'\1')

In [14]:
#Merging all columns that contain user preferences and interests and traits
df['Preference'] = df['Interests']+ ' ' +df['Perfect_match']+ ' ' +df['Personality']

df.head()

Unnamed: 0  Gender    Location        Education               Religion  \
0           0  Female   Rotterdam      High School               Atheist    
1           1    Male   Rotterdam  Master's Degree  Nothing in particular   
2           2  Female  Rotterdam       High School  Nothing in particular   
3           3  Female   Rotterdam      High School               Atheist    
4           4  Female   Rotterdam      High School  Nothing in particular   

                                         Personality  Imagination  Artistic  \
0                                                               4         3   
1  Energetic person who trives to get the best ou...            4         1   
2     Sensitive, caring, independent, enthusiastic              4         2   
3                                                               4         3   
4                           Spontaneous and cheerful            4         1   

   Sociable  Reserved  Lazy  Nervous  Trusting  Thorough  Relaxed  \
0         4         2     2        4         2         3        1   
1         4         4     3        5         5         4        2   
2         4         2     4        4         3         4        2   
3         4         2     2        4         2         3        1   
4         5         2     4        5         5         4        2   

   Fault_others                                      Perfect_match  \
0             1  Someone who is social and wants to go do stuff...   
1             4  Someone who's interested in the same music or ...   
2             1  Someone who helps me step outside of my comfor...   
3             1  Someone who is social and wants to go do stuff...   
4             3  Being able to laugh together and do fun things...   

                                           Interests  \
0  Working and helping kids Listening to music, r...   
1  Music, listening to music, writing music and m...   
2  The environment and climate change Reading, li...   
3  Working and helping kids music guitar skateboa...   
4  Animals and specifically dogs and all dog care...   

                                          Preference  
0  Working and helping kids Listening to music, r...  
1  Music, listening to music, writing music and m...  
2  The environment and climate change Reading, li...  
3  Working and helping kids music guitar skateboa...  
4  Animals and specifically dogs and all dog care...

In [15]:
#transform everything to lower case
df['Preference'] = df['Preference'].apply(lambda x:x.lower())
df.head()

Unnamed: 0  Gender    Location        Education               Religion  \
0           0  Female   Rotterdam      High School               Atheist    
1           1    Male   Rotterdam  Master's Degree  Nothing in particular   
2           2  Female  Rotterdam       High School  Nothing in particular   
3           3  Female   Rotterdam      High School               Atheist    
4           4  Female   Rotterdam      High School  Nothing in particular   

                                         Personality  Imagination  Artistic  \
0                                                               4         3   
1  Energetic person who trives to get the best ou...            4         1   
2     Sensitive, caring, independent, enthusiastic              4         2   
3                                                               4         3   
4                           Spontaneous and cheerful            4         1   

   Sociable  Reserved  Lazy  Nervous  Trusting  Thorough  Relaxed  \
0         4         2     2        4         2         3        1   
1         4         4     3        5         5         4        2   
2         4         2     4        4         3         4        2   
3         4         2     2        4         2         3        1   
4         5         2     4        5         5         4        2   

   Fault_others                                      Perfect_match  \
0             1  Someone who is social and wants to go do stuff...   
1             4  Someone who's interested in the same music or ...   
2             1  Someone who helps me step outside of my comfor...   
3             1  Someone who is social and wants to go do stuff...   
4             3  Being able to laugh together and do fun things...   

                                           Interests  \
0  Working and helping kids Listening to music, r...   
1  Music, listening to music, writing music and m...   
2  The environment and climate change Reading, li...   
3  Working and helping kids music guitar skateboa...   
4  Animals and specifically dogs and all dog care...   

                                          Preference  
0  working and helping kids listening to music, r...  
1  music, listening to music, writing music and m...  
2  the environment and climate change reading, li...  
3  working and helping kids music guitar skateboa...  
4  animals and specifically dogs and all dog care...

In [16]:
#Import TfIdfVectorizer from scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer

text = df['Preference'].values.astype('U') #Converting text from the df and convert it to Unicode
tfidf = TfidfVectorizer(stop_words='english') #Remove stopwords

tfidf = tfidf.fit(text) #We fit the model with the words from the preference text
tfidf

feature_names = tfidf.get_feature_names() #Get the words from the vocabulary
#feature_names
print(f"There are {len(feature_names)} words in the vocabulary. A selection: {feature_names[42:62]}")


#Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix = tfidf.fit_transform(df['Preference'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape

There are 530 words in the vocabulary. A selection: ['bubbly', 'busy', 'buy', 'calm', 'card', 'care', 'careful', 'caring', 'cat', 'cats', 'catvideo', 'challenge', 'challenges', 'challenging', 'change', 'chaotic', 'characteristics', 'charge', 'chat', 'chatting']


(65, 530)

In [17]:
# Import linear_kernel
from sklearn.metrics.pairwise import linear_kernel

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

cosine_sim 

array([[1.        , 0.19384443, 0.11949942, ..., 0.        , 0.17025676,
        0.07063524],
       [0.19384443, 1.        , 0.11601785, ..., 0.02346374, 0.03248068,
        0.07873504],
       [0.11949942, 0.11601785, 1.        , ..., 0.        , 0.03309517,
        0.02292131],
       ...,
       [0.        , 0.02346374, 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.17025676, 0.03248068, 0.03309517, ..., 0.        , 1.        ,
        0.17010148],
       [0.07063524, 0.07873504, 0.02292131, ..., 0.        , 0.17010148,
        1.        ]])

In [18]:
#Add index instead of names to preserve respondents privacy
df['User'] = np.arange(len(df))

In [19]:
#create df of the similarity scores
df = pd.DataFrame(cosine_sim, columns=df.index, index=df['User']).reset_index()
df.head()

User         0         1         2         3         4         5         6  \
0     0  1.000000  0.193844  0.119499  0.916507  0.000000  0.140748  0.144923   
1     1  0.193844  1.000000  0.116018  0.239162  0.085154  0.000000  0.195857   
2     2  0.119499  0.116018  1.000000  0.123214  0.014100  0.000000  0.047028   
3     3  0.916507  0.239162  0.123214  1.000000  0.000000  0.119595  0.184716   
4     4  0.000000  0.085154  0.014100  0.000000  1.000000  0.000000  0.064400   

          7         8  ...        55        56        57        58        59  \
0  0.000000  0.166586  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
1  0.031349  0.026764  ...  0.112333  0.013252  0.073603  0.022717  0.043633   
2  0.063470  0.039114  ...  0.019505  0.027005  0.035354  0.000000  0.083269   
3  0.000000  0.141551  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
4  0.000000  0.023900  ...  0.121097  0.060818  0.077977  0.035829  0.074169   

         60        61        62        63        64  
0  0.199748  0.034586  0.000000  0.170257  0.070635  
1  0.234570  0.133070  0.023464  0.032481  0.078735  
2  0.079758  0.110528  0.000000  0.033095  0.022921  
3  0.235034  0.029388  0.000000  0.144670  0.090030  
4  0.000000  0.108126  0.079767  0.083149  0.000000  

[5 rows x 66 columns]

# Create df with similarity scores from both RS 1 and 2

In [20]:
#Merge similarity dataframes to one with al similarity scores
df = pd.merge(df, df_num_cat, on="User")

#Drop the user column *this columns does not need to be used for making similarity scores*
df1 = df.drop(columns=['User'])
df1 = pd.DataFrame(df1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 65 entries, 0 to 64
Columns: 131 entries, User to 64_y
dtypes: float64(130), int64(1)
memory usage: 67.0 KB


In [21]:
df = df.reset_index()
indices = pd.Series(df.index, index=df['User']).drop_duplicates()

In [22]:
# Function that takes in user as input and outputs most similar users
def get_recommendations(User, df1=df1):
    # Get the index of the users that matches the df
    idx = indices[User]

    # Get the pairwsie similarity scores of all users with df
    sim_scores = list(enumerate(df1[idx])) 
    
    # Sort the user based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar users
    sim_scores = sim_scores[1:12]

    # Get the user indices
    match_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar users
    return df['User'].iloc[match_indices]

In [23]:
#User where recommendations need to be made for
user = 7

#Print recommendations
def recommendation (x):
    print ('Your top 10 is:')
    recommendations = get_recommendations(user, similarity) 
    return recommendations

recommendation(1)

Your top 10 is:


55    55
36    36
19    19
13    13
30    30
12    12
35    35
62    62
42    42
58    58
28    28
Name: User, dtype: int64